# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population_Proportion_That_Took_Trip',
            fields=[
                ('population_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_id', models.IntegerField()),
                ('proportion', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
            ],
        ),
    ]
