# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news', models.CharField(max_length=2000)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
