# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
