# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170929_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='date',
            new_name='created_at',
        ),
    ]
