# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdf_Allocation',
            fields=[
                ('cdfallocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcounty_id', models.IntegerField()),
                ('cdfallocation', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        # migrations.CreateModel(
        #     name='County_Budget_Allocation',
        #     fields=[
        #         ('budget_allocation_id', models.AutoField(db_column='budget_allocation_ID', primary_key=True, serialize=False)),
        #         ('recurrent', models.CharField(max_length=255)),
        #         ('development', models.CharField(max_length=255)),
        #         ('total', models.CharField(max_length=255)),
        #         ('year', models.CharField(max_length=20)),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='County_Expenditure',
        #     fields=[
        #         ('countyexpenditure_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('compensation_employees', models.CharField(max_length=250)),
        #         ('goods_services', models.CharField(max_length=250)),
        #         ('subsidies', models.CharField(max_length=250)),
        #         ('grants_internationalorganisation', models.CharField(max_length=250)),
        #         ('grants_governmentunits', models.CharField(max_length=250)),
        #         ('othergrants', models.CharField(max_length=250)),
        #         ('capitalgrants', models.CharField(max_length=250)),
        #         ('socialbenefits', models.CharField(max_length=250)),
        #         ('otherexpense', models.CharField(max_length=250)),
        #         ('buildingstructures', models.CharField(max_length=250)),
        #         ('plantmachinery_equipment', models.CharField(max_length=250)),
        #         ('inventories', models.CharField(max_length=250)),
        #         ('otherassets', models.CharField(max_length=250)),
        #         ('acquisition_financialassets', models.CharField(max_length=250)),
        #         ('interest_debt', models.CharField(max_length=250)),
        #         ('total', models.CharField(max_length=250)),
        #         ('year', models.CharField(max_length=250)),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #     ],
        # ),
        migrations.CreateModel(
            name='County_Revenue',
            fields=[
                ('county_revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('revenue_estimates', models.CharField(max_length=200)),
                ('conditional_grant', models.CharField(max_length=200)),
                ('equitable_share', models.CharField(max_length=200)),
                ('total_revenue', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Economic_Classification_Revenue',
            fields=[
                ('economicrevenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('taxes_income_profits_capitalgains', models.CharField(max_length=250)),
                ('taxes_property', models.CharField(max_length=250)),
                ('taxes_vat', models.CharField(max_length=250)),
                ('taxes_othergoodsandservices', models.CharField(max_length=250)),
                ('taxes_internationaltrade_transactions', models.CharField(max_length=250)),
                ('other_taxes_notelsewhereclasified', models.CharField(max_length=250)),
                ('totaltax_revenue', models.CharField(max_length=250)),
                ('socialsecuritycontributions', models.CharField(max_length=250)),
                ('property_income', models.CharField(max_length=250)),
                ('sale_goodsandservices', models.CharField(max_length=250)),
                ('fines_penaltiesandforfeitures', models.CharField(max_length=250)),
                ('repayments_domesticlending', models.CharField(max_length=250)),
                ('other_receiptsnotelsewhereclassified', models.CharField(max_length=250)),
                ('total_nontax_revenue', models.CharField(max_length=250)),
                ('total', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Excise_Revenue_Commodity',
        #     fields=[
        #         ('excise_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.CharField(max_length=250)),
        #         ('beer', models.CharField(max_length=250)),
        #         ('cigarettes', models.CharField(max_length=250)),
        #         ('mineral_waters', models.CharField(max_length=250)),
        #         ('wines_spirits', models.CharField(max_length=250)),
        #         ('other_commodities', models.CharField(max_length=250)),
        #         ('total', models.CharField(max_length=250)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Money_Banking_Index',
        #     fields=[
        #         ('institution_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('financial_institution', models.CharField(max_length=100)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Money_Banking_Institutions',
        #     fields=[
        #         ('moneybanking_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('subcounty_id', models.IntegerField()),
        #         ('number', models.IntegerField()),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #         ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Money_Banking_Index')),
        #     ],
        # ),
        migrations.CreateModel(
            name='National_Government_Expenditure',
            fields=[
                ('government_expenditure_id', models.AutoField(primary_key=True, serialize=False)),
                ('acquisition_nonfinancial_assets', models.CharField(max_length=250)),
                ('acquisition_financial_assets', models.CharField(max_length=250)),
                ('loans_repayments', models.CharField(max_length=250)),
                ('compensation_employees', models.CharField(max_length=250)),
                ('goods_services', models.CharField(max_length=250)),
                ('subsidies', models.CharField(max_length=250)),
                ('interest', models.CharField(max_length=250)),
                ('grants', models.CharField(max_length=250)),
                ('other_expense', models.CharField(max_length=250)),
                ('social_benefits', models.CharField(max_length=250)),
                ('capital_grants', models.CharField(max_length=250)),
                ('total', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='National_Government_Expenditure_Purpose',
            fields=[
                ('purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=20)),
                ('general_publicservices', models.CharField(max_length=250)),
                ('public_debttransactions', models.CharField(max_length=250)),
                ('transfers', models.CharField(max_length=250)),
                ('defense', models.CharField(max_length=250)),
                ('order_safety', models.CharField(max_length=250)),
                ('economic_commercial_labor', models.CharField(max_length=250)),
                ('agriculture', models.CharField(max_length=250)),
                ('fuel_energy', models.CharField(max_length=250)),
                ('mining_manufacturing_construction', models.CharField(max_length=250)),
                ('transport', models.CharField(max_length=250)),
                ('communication', models.CharField(max_length=250)),
                ('other_industries', models.CharField(max_length=250)),
                ('environmental_protection', models.CharField(max_length=250)),
                ('housing_communityamenities', models.CharField(max_length=250)),
                ('health', models.CharField(max_length=250)),
                ('recreation_culture_religion', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=250)),
                ('socialprotection', models.CharField(max_length=250)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Outstanding_Debt_International_Organization',
        #     fields=[
        #         ('outstanding_debt', models.AutoField(primary_key=True, serialize=False)),
        #         ('ida', models.CharField(max_length=250)),
        #         ('eec_eib', models.CharField(max_length=250)),
        #         ('imf', models.CharField(max_length=250)),
        #         ('adf_adb', models.CharField(max_length=250)),
        #         ('commercial_banks', models.CharField(max_length=250)),
        #         ('others', models.CharField(max_length=250)),
        #         ('year', models.CharField(max_length=50)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Outstanding_Debt_Lending_Country',
            fields=[
                ('lending_country_id', models.AutoField(primary_key=True, serialize=False)),
                ('germany', models.CharField(max_length=250)),
                ('japan', models.CharField(max_length=250)),
                ('france', models.CharField(max_length=250)),
                ('usa', models.CharField(max_length=250)),
                ('netherlands', models.CharField(max_length=250)),
                ('denmark', models.CharField(max_length=250)),
                ('finland', models.CharField(max_length=250)),
                ('china', models.CharField(max_length=250)),
                ('belgium', models.CharField(max_length=250)),
                ('other', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
