# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_hospitalbedsandcots'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdf_Allocation_By_Constituency',
            fields=[
                ('cdf_allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcounty_id', models.IntegerField()),
                ('cdf_amount', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditures_And_Revenues',
            fields=[
                ('exp_rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('expenditure', models.BigIntegerField()),
                ('revenue', models.BigIntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='National_Government_Allocation',
            fields=[
                ('nat_govt_fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('allocated_funds', models.BigIntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
