# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cdf_allocation_by_constituency_expenditures_and_revenues_national_government_allocation'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='county_expenditure',
        #     name='year',
        #     field=models.IntegerField(),
        # ),
    ]
