# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20171010_1451'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='county_expenditure',
        #     name='year',
        #     field=models.CharField(max_length=250),
        # ),
    ]
