# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20171011_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation_And_Disbursement_Of_Funds_Social_Protection',
            fields=[
                ('social_fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_beneficiaries', models.IntegerField()),
                ('allocation', models.BigIntegerField()),
                ('direct_cash_disbursement', models.BigIntegerField()),
                ('social_fund_category', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
