# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_excise_revenue_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excise_Revenue_Commodity',
            fields=[
                ('excise_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=100)),
                ('beer', models.DecimalField(decimal_places=2, max_digits=65)),
                ('cigarettes', models.DecimalField(decimal_places=2, max_digits=65)),
                ('mineral_waters', models.DecimalField(decimal_places=2, max_digits=65)),
                ('wines_spirits', models.DecimalField(decimal_places=2, max_digits=65)),
                ('other_commodities', models.DecimalField(decimal_places=2, max_digits=65)),
                ('total', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
    ]
