# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_excise_revenue_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outstanding_Debt_International_Organization',
            fields=[
                ('outstanding_debt_id', models.AutoField(primary_key=True, serialize=False)),
                ('ida', models.DecimalField(decimal_places=2, max_digits=15)),
                ('eec_eib', models.DecimalField(decimal_places=2, max_digits=15)),
                ('imf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adf_adb', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commercial_banks', models.DecimalField(decimal_places=2, max_digits=15)),
                ('others', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
    ]
