# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_classification_national_government_expenditure_function_economic_analysis_of_national_government_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure_Functions_County_Governments',
            fields=[
                ('cofog_id', models.AutoField(primary_key=True, serialize=False)),
                ('general_public_services', models.DecimalField(decimal_places=10, max_digits=65)),
                ('general_economic_affairs', models.DecimalField(decimal_places=10, max_digits=65)),
                ('economic_affairs_agriculture', models.DecimalField(decimal_places=10, max_digits=65)),
                ('economic_affairs_transport', models.DecimalField(decimal_places=10, max_digits=65)),
                ('other_economic_affairs', models.DecimalField(decimal_places=10, max_digits=65)),
                ('environmental_protection', models.DecimalField(decimal_places=10, max_digits=65)),
                ('housing_community_ammenities', models.DecimalField(decimal_places=10, max_digits=65)),
                ('health', models.DecimalField(decimal_places=10, max_digits=65)),
                ('recreation_culture_religion', models.DecimalField(decimal_places=10, max_digits=65)),
                ('education', models.DecimalField(decimal_places=10, max_digits=65)),
                ('social_protection', models.DecimalField(decimal_places=10, max_digits=65)),
                ('total', models.DecimalField(decimal_places=10, max_digits=65)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
