# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_statistics', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='top_ten_death_causes_2014',
        #     old_name='cause_id',
        #     new_name='cause',
        # ),
    ]
