# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_distributionofoutpatientvisitsbytypeofhealthcareprovider_insurance_coverage_by_counties_and_types_re'),
        ('vital_statistics', '0002_auto_20170828_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Ten_Death_Causes',
            fields=[
                ('count_id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.FloatField()),
                ('total', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vital_statistics.Death_Causes')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
