# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_distributionofoutpatientvisitsbytypeofhealthcareprovider_insurance_coverage_by_counties_and_types_re'),
        ('transport_and_communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure_On_Roads',
            fields=[
                ('expenditure_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('expenditure', models.BigIntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_Of_Ongoing_Roads_Programme',
            fields=[
                ('road_id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_completion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_project_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
