# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue_Collection_By_Amount',
            fields=[
                ('tradeandcommerce_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Collection_By_Id',
            fields=[
                ('revenuecollection_id', models.AutoField(primary_key=True, serialize=False)),
                ('revenuecollection_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Collection_By_Title',
            fields=[
                ('tradeandcommerce_by_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('tradeandcommerce_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='revenue_collection_by_amount',
            name='revenuecollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_and_commerce.Revenue_Collection_By_Id'),
        ),
    ]
