# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_sectors'),
        ('trade_and_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading_Centres',
            fields=[
                ('tradeandcommerce_centre_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Trading_Centres_Ids',
            fields=[
                ('trading_centre_id', models.AutoField(primary_key=True, serialize=False)),
                ('trading_centre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='trading_centres',
            name='trading_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_and_commerce.Trading_Centres_Ids'),
        ),
    ]
