# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_and_commerce', '0002_auto_20170918_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Of_Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('amount_in_millions', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Import_Trade_Africa_Countries',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
                ('zones', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('values', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantities_Principal_Domestic_Exports',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantities_Principal_Imports',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=100)),
                ('unit_of_quantity', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Values_Of_Principal_Domestic_Exports',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('values', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Values_Of_Principal_Imports',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
