# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('political_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcounty_id', models.IntegerField()),
                ('county_ward', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
