# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment_Public_Sector',
            fields=[
                ('wage_employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('wage_employment', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employment_public_sector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labour.Sectors'),
        ),
    ]
