# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average_Wage_Earnings_Per_Employee_Private_Sector',
            fields=[
                ('wage_earnings_id', models.AutoField(primary_key=True, serialize=False)),
                ('private_sector', models.CharField(max_length=120)),
                ('wage_earnings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Average_Wage_Earnings_Per_Employee_Public_Sector',
            fields=[
                ('wage_earnings_id', models.AutoField(primary_key=True, serialize=False)),
                ('public_sector', models.CharField(max_length=120)),
                ('wage_earnings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Memorandum_Items_In_Public_Sector',
            fields=[
                ('memorandum_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('memorandum_item', models.CharField(max_length=100)),
                ('wage_earnings', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Total_Recorded_Employment',
            fields=[
                ('total_employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_category', models.CharField(max_length=100)),
                ('total_employment', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wage_Employment_By_Industry_And_Sex',
            fields=[
                ('wage_employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=120)),
                ('wage_employment', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wage_Employment_By_Industry_In_Private_Sector',
            fields=[
                ('wage_employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('private_sector', models.CharField(max_length=120)),
                ('wage_employment', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wage_Employment_By_Industry_In_Public_Sector',
            fields=[
                ('wage_employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('public_sector', models.CharField(max_length=100)),
                ('wage_employment', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
