# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_sectors'),
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land_Potential',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcounty_id', models.IntegerField()),
                ('value', models.FloatField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Land_Potential_Ids',
            fields=[
                ('potential_id', models.AutoField(primary_key=True, serialize=False)),
                ('landPotential', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='land_potential',
            name='potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.Land_Potential_Ids'),
        ),
    ]
