# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_auto_20170918_0926'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Area_Under_Sugarcane_Area_Harvested_Production_And_Average_Yield',
        #     fields=[
        #         ('area_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('area_under_cane_ha', models.IntegerField()),
        #         ('area_harvested_ha', models.IntegerField()),
        #         ('production_tonnes', models.IntegerField()),
        #         ('average_yield_tonnes_per_ha', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Production_Area_And_Average_Yield_Of_Coffee_By_Type_Of_Grower',
        #     fields=[
        #         ('category_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('cooperatives', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('estates', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('unit', models.CharField(max_length=100)),
        #         ('year', models.CharField(max_length=100)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Production_Area_And_Average_Yield_Of_Tea_By_Type_Of_Grower',
        #     fields=[
        #         ('category_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('smallholders', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('estates', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('unit', models.CharField(max_length=100)),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Production_Of_Livestock_And_Dairy_Products',
        #     fields=[
        #         ('product_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('by_product', models.CharField(max_length=100)),
        #         ('unit', models.CharField(max_length=100)),
        #         ('value', models.DecimalField(decimal_places=10, max_digits=10)),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
    ]
