# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_area_under_sugarcane_area_harvested_production_avg_yield_production_area_average_yield_coffee_type_o'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Under_Sugarcane_Harvested_Production_Avg_Yield',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_under_cane_ha', models.IntegerField()),
                ('area_harvested_ha', models.IntegerField()),
                ('production_tonnes', models.IntegerField()),
                ('average_yield_tonnes_per_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
