# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_months'),
        ('agriculture', '0005_area_under_sugarcane_harvested_production_avg_yield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Of_Agricultural_Land',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('high_potential', models.IntegerField()),
                ('medium_potential', models.IntegerField()),
                ('low_potential', models.IntegerField()),
                ('total_land', models.IntegerField()),
                ('all_other_land', models.IntegerField()),
                ('total_land_area', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
