# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0008_production_of_livestock_and_dairy_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Of_Livestock_And_Dairy_Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('by_product', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=7, max_digits=30)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
