# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_months'),
        ('money_and_banking', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Commercial_Banks_Bills_Loans_Advances',
        #     fields=[
        #         ('bills_loans_advances_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('sector', models.CharField(max_length=100)),
        #         ('sub_sector', models.CharField(max_length=100)),
        #         ('amount', models.IntegerField()),
        #         ('year', models.DateField()),
        #         ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Months')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Interest_Rates',
        #     fields=[
        #         ('interest_rates_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('bank_loans_and_advances_weighted_average_rates', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('average_deposit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('year', models.DateField()),
        #         ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Months')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Monetary_Indicators_Broad_Money_Supply',
        #     fields=[
        #         ('broad_money_supply_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.DateField()),
        #         ('broad_money_supply', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Monetary_Indicators_Domestic_Credit',
        #     fields=[
        #         ('domestic_credit_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.DateField()),
        #         ('private_and_other_public_bodies', models.IntegerField()),
        #         ('national_government', models.IntegerField()),
        #         ('total', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Selected_Real_Principal_Interest_Rates',
        #     fields=[
        #         ('interest_rate_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('selected_real_principal_interest_rates', models.CharField(max_length=100)),
        #         ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('year', models.DateField()),
        #     ],
        # ),
    ]
