# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_and_banking', '0002_commercial_banks_bills_loans_advances_interest_rates_monetary_indicators_broad_money_supply_monetary'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Inflation_Rates',
        #     fields=[
        #         ('interest_rate_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('year', models.DateField()),
        #     ],
        # ),
    ]
