# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_months'),
        ('money_and_banking', '0003_inflation_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_institution', models.CharField(max_length=100)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Inflation_Rates',
        #     fields=[
        #         ('inflation_rate_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('year', models.DateField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('moneybanking_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcounty_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_and_banking.Index')),
            ],
        ),
    ]
