# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_enrollmentsecondaryschoolsbylevelandsex_es_educational_institutions_public_tivet_es_educational_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_Degree_Diploma_Programs',
            fields=[
                ('approved_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('approved_degree_programmes', models.IntegerField()),
                ('approved_private_university_degreeprogrammes', models.IntegerField()),
                ('validated_diploma_programmes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollmentBySexTechnicalInstitutions',
            fields=[
                ('student_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollmentPublicUniversities',
            fields=[
                ('student_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('undergraduates', models.IntegerField()),
                ('postgraduates', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
    ]
