# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_registered_active_nhif_members_by_county_registered_active_nhif_members_nationally'),
        ('education', '0003_approved_degree_diploma_programs_studentenrollmentbysextechnicalinstitutions_studentenrollmentpublic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edstat_Ecde_Enrollment_And_Enrollment_Rates_By_County',
            fields=[
                ('ecde_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ecde_enrollment', models.IntegerField()),
                ('gross_enrollment_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_enrollment_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Edstat_Kcpe_Examination_Candidature',
            fields=[
                ('candidature_id', models.AutoField(primary_key=True, serialize=False)),
                ('kcpe_candidature', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Edstat_Kcpe_Examination_Results_By_Subject',
            fields=[
                ('kcpe_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('kcpe_result', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Edstat_Kcse_Examination_Results',
            fields=[
                ('kcse_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_candidates', models.IntegerField()),
                ('kcse_grade', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Edstat_Primary_Enrollment_Enrollment_Rates_County',
            fields=[
                ('primary_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_enrollment', models.IntegerField()),
                ('gross_enrollment_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_enrollment_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Edstat_Secondary_Enrollment_Enrollment_Rates_County',
            fields=[
                ('secondary_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('secondary_enrollment', models.IntegerField()),
                ('gross_enrollment_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_enrollment_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
