# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_edstat_ecde_enrollment_and_enrollment_rates_by_county_edstat_kcpe_examination_candidature_edstat_kcp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_Of_Candidates_By_Sex_In_Kcse',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('proportion', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
