# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_primary_school_enrolments_by_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Primary_School_Teachers_By_Sex',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('proportion', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
