# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_public_primary_school_teachers_by_sex'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Public_Primaryteachers_TrainingCollege_Enrolment_By_Sex',
        #     fields=[
        #         ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.IntegerField()),
        #         ('number', models.IntegerField()),
        #         ('proportion', models.DecimalField(decimal_places=1, max_digits=10)),
        #         ('gender', models.CharField(max_length=10)),
        #     ],
        # ),
    ]
