# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_public_primaryteachers_trainingcollege_enrolment_by_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_Primaryteachers_TrainingCollege_Enrolment',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('proportion', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Public_Secondary_School_Teachers_By_Sex',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('proportion', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_School_Enrolment_By_Sex',
            fields=[
                ('enrolment_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('boys', models.IntegerField()),
                ('girls', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage_girls', models.DecimalField(decimal_places=1, max_digits=10)),
                ('parity_index', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
