# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_public_primaryteachers_trainingcollege_enrolment_public_secondary_school_teachers_by_sex_secondary_s'),
    ]

    operations = [
        
    ]
