# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_population_distribution_above_three_school_attendance_status'),
    ]

    operations = [

    ]
