# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20180531_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_AboveThreeYears_Highestlevel_Reached',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_id', models.IntegerField()),
                ('pre_primary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('primary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('post_primary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('secondary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('college', models.DecimalField(decimal_places=1, max_digits=10)),
                ('university', models.DecimalField(decimal_places=1, max_digits=10)),
                ('madrassa_duksi', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
            ],
        ),

        migrations.CreateModel(
            name='Population_Distribution_Above_Three_School_Attendance',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_id', models.IntegerField()),
                ('currently_attending', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_attending', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
            ],
        ),
    ]
