# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_distribution_abovethreeyears_highestlevel_reached_distribution_abovethreeyears_school_attendance_tra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_AboveThreeYears_Training',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_id', models.IntegerField()),
                ('ever_attended', models.DecimalField(decimal_places=1, max_digits=10)),
                ('never_attended', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
            ],
        ),
    ]
