# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_distribution_three_twentyfour_schoolattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gross_Attendance_Ratio_By_Level',
            fields=[
                ('ratio_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_id', models.IntegerField()),
                ('pre_primary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('primary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('secondary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Net_Attendance_Ratio_By_Level',
            fields=[
                ('ratio_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_id', models.IntegerField()),
                ('pre_primary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('primary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('secondary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
