# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_gross_attendance_ratio_by_level_net_attendance_ratio_by_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_Highest_Education_Qualification',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_id', models.IntegerField()),
                ('none', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cpe_kcpe', models.DecimalField(decimal_places=1, max_digits=10)),
                ('kape', models.DecimalField(decimal_places=1, max_digits=10)),
                ('kjse', models.DecimalField(decimal_places=1, max_digits=10)),
                ('kce_kcse', models.DecimalField(decimal_places=1, max_digits=10)),
                ('kace_eaace', models.DecimalField(decimal_places=1, max_digits=10)),
                ('certificate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('diploma', models.DecimalField(decimal_places=1, max_digits=10)),
                ('degree', models.DecimalField(decimal_places=1, max_digits=10)),
                ('post_literacy_cert', models.DecimalField(decimal_places=1, max_digits=10)),
                ('other', models.DecimalField(decimal_places=1, max_digits=10)),
                ('not_stated', models.DecimalField(decimal_places=1, max_digits=10)),
                ('no_of_individuals', models.IntegerField()),
            ],
        ),
    ]
