# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Dataset',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('dataset', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
