# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Per_Change_In_Quantum_Indices_Of_Man_Production',
            fields=[
                ('percentage_change_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=200)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantum_Indices_Of_Manufacturing_Production',
            fields=[
                ('quantum_indice_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=200)),
                ('quantum_indice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
