# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0003_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes_Reported_To_Police_By_Command_Stations',
            fields=[
                ('crime_id', models.AutoField(primary_key=True, serialize=False)),
                ('crimes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Offence_By_Sex_And_Command_Stations',
            fields=[
                ('offence_id', models.AutoField(primary_key=True, serialize=False)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Voters_By_County_And_By_Sex',
            fields=[
                ('voters_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_counties_id', models.IntegerField()),
                ('reg_voters', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
