# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases_Forwarded_And_Action_Taken',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_taken', models.CharField(max_length=100)),
                ('no_of_recommendations', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cases_Handled_By_Ethics_Commision',
            fields=[
                ('cases_handled_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('no_cases', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Cases_Handled_By_Various_Courts',
        #     fields=[
        #         ('court_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('court', models.CharField(max_length=100)),
        #         ('filled', models.IntegerField()),
        #         ('pending', models.IntegerField()),
        #         ('disposed_of', models.IntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='Convicted_Prison_Population_By_Age_And_Sex',
            fields=[
                ('convict_population', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Convicted_Prisoners_By_Type_Of_Offence_And_Sex',
            fields=[
                ('convicted_offence_type', models.AutoField(primary_key=True, serialize=False)),
                ('offence', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Environmental_Crimes_Reported_To_Nema',
            fields=[
                ('crime_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_case', models.CharField(max_length=100)),
                ('no_of_cases', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Number_Of_Police_Prisons_And_Probation_Officers',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offences_Committed_Against_Morality',
            fields=[
                ('offences_commiited_against_morality_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persons_Reported_To_Have_Committed_Homicide_By_Sex',
            fields=[
                ('offence_id', models.AutoField(primary_key=True, serialize=False)),
                ('offence', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persons_Reported_To_Have_Committed_Robbery_And_Theft',
            fields=[
                ('offence_id', models.AutoField(primary_key=True, serialize=False)),
                ('offence', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
