# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_current_use_of_contraception_by_county_distributionofoutpatientvisitsbytypeofhealthcareprovider_2013'),
        ('governance', '0002_cases_forwarded_and_action_taken_cases_handled_by_ethics_commision_cases_handled_by_various_courts_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Average_Population_Of_Prisoners_By_Sex',
            fields=[
                ('daily_population_prisoners_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Firearms_And_Ammunition_Recovered_Or_Surrendered',
        #     fields=[
        #         ('category_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('recovered', models.IntegerField()),
        #         ('surrendered', models.IntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='Identity_Cards_Made_Processed_And_Collected',
            fields=[
                ('nprs_id', models.AutoField(primary_key=True, serialize=False)),
                ('npr_apps_made', models.IntegerField()),
                ('npr_ids_prod', models.IntegerField()),
                ('npr_ids_collected', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Magistrates_Judges_And_Practicing_Lawyers',
        #     fields=[
        #         ('category_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('male', models.IntegerField()),
        #         ('female', models.IntegerField()),
        #         ('total', models.IntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='Murder_Cases_And_Convictions_Obtained_By_High_Court',
            fields=[
                ('reg_murder_convictions_obtained_id', models.AutoField(primary_key=True, serialize=False)),
                ('court_station', models.CharField(max_length=100)),
                ('registered_murder_cases', models.IntegerField()),
                ('murder_convictions_obtained', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Number_Of_Refugees_By_Age_And_Sex',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('children', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offenders_Serving',
            fields=[
                ('offence_id', models.AutoField(primary_key=True, serialize=False)),
                ('offence', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passports_Work_Permits_And_Foreigners_Registered',
            fields=[
                ('passports_permits_registered_foreigners_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_issued', models.IntegerField()),
                ('foreign_nat_reg', models.IntegerField()),
                ('work_permit_issued', models.IntegerField()),
                ('work_permit_ren', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='People_Reported_To_Have_Committed_Offence_Related_To',
        #     fields=[
        #         ('people_offence_related_drugs_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('offence', models.CharField(max_length=100)),
        #         ('male', models.IntegerField()),
        #         ('female', models.IntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        migrations.CreateModel(
            name='Prison_Population_By_Sentence_Duration_And_Sex',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Public_Assets_Traced_Recovered_And_Loss_Averted',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('public_assets_traced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('public_assets_recovered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loss_averted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
