# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_daily_average_population_of_prisoners_by_sex_firearms_and_ammunition_recovered_or_surrendered_identi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firearms_And_Ammunition_Recovered_Or_Surrendered',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('rifles', models.IntegerField()),
                ('pistols', models.IntegerField()),
                ('toy_pistols', models.IntegerField()),
                ('ammunition', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Magistrates_Judges_And_Practicing_Lawyers',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Persons_Reported_To_Have_Committed_Offences_Related_To_Drugs',
        #     fields=[
        #         ('offence_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('offence', models.CharField(max_length=100)),
        #         ('male', models.IntegerField()),
        #         ('female', models.IntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
    ]
