# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_firearms_and_ammunition_recovered_or_surrendered_magistrates_judges_and_practicing_lawyers_persons_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons_Reported_Committed_Offences_Related_To_Drugs',
            fields=[
                ('offence_id', models.AutoField(primary_key=True, serialize=False)),
                ('offence', models.CharField(max_length=100)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
