# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0007_auto_20171109_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation_In_Key_Decision_Making_Positions_By_Sex',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('female', models.IntegerField()),
                ('male', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Women_Groups_Registration_Contributions_Uwezo_Funds',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_beneficiaries', models.IntegerField()),
                ('uwezo_fund_disbursed', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Women_Groups_Registration_Contributions_Women_Enterprise_Fund',
        #     fields=[
        #         ('group_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('no_of_beneficiaries', models.IntegerField()),
        #         ('women_enterprise_fund', models.IntegerField()),
        #         ('year', models.CharField(max_length=10)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Women_Groups_Registration_Contributions_Women_Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('membership', models.IntegerField()),
                ('group_contributions', models.BigIntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
