# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_participation_in_key_decision_making_positions_by_sex_women_groups_registration_contributions_uwezo_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Women_Groups_Registration_Cont_Women_Enterprise_Fund',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_beneficiaries', models.IntegerField()),
                ('women_enterprise_fund', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
