# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_experienceof_domestic_violence_by_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experienceof_Domestic_Violence_By_Marital_Success',
            fields=[
                ('woman_id', models.AutoField(primary_key=True, serialize=False)),
                ('marital_status', models.CharField(max_length=30)),
                ('percentage_experienced_physical_violence', models.DecimalField(decimal_places=1, max_digits=10)),
                ('percentage_experienced_sexual_violence', models.DecimalField(decimal_places=1, max_digits=10)),
                ('percentage_experienced_physical_and_sexual_violence', models.DecimalField(decimal_places=1, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
