# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_experienceof_domestic_violence_by_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge_And_Prevalence_Of_Female_Circumcision',
            fields=[
                ('woman_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=10)),
                ('percentage_women_heard_of_FC', models.DecimalField(decimal_places=1, max_digits=10)),
                ('percentage_women_not_heard_of_FC', models.DecimalField(decimal_places=1, max_digits=10)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
