# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0013_knowledge_and_prevalence_of_female_circumcision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members_Of_NationalAssembly_and_Senators',
            fields=[
                ('woman_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('women', models.IntegerField()),
                ('men', models.IntegerField()),
                ('total', models.IntegerField()),
                ('women_percentage', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
