# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0017_total_prisoners_committed_for_debt_bysex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevalence_Female_Circumcision_And_Type',
            fields=[
                ('persons_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=20)),
                ('cut_no_flesh_removed', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cut_flesh_removed', models.DecimalField(decimal_places=1, max_digits=10)),
                ('sewn_closed', models.DecimalField(decimal_places=1, max_digits=10)),
                ('others', models.DecimalField(decimal_places=1, max_digits=10)),
                ('percentage_women_circumcised', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
