# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationBySexHouseholdsDensityAndCensusYears',
            fields=[
                ('census_population_id', models.AutoField(primary_key=True, serialize=False)),
                ('male', models.CharField(max_length=100)),
                ('female', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('hhs', models.CharField(max_length=100)),
                ('av_hh_size', models.CharField(max_length=100)),
                ('approx_area', models.CharField(max_length=100)),
                ('density', models.CharField(max_length=100)),
                ('census_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationProjectionsBySelectedAgeGroup',
            fields=[
                ('population_projection_id', models.AutoField(primary_key=True, serialize=False)),
                ('range_0_4', models.CharField(max_length=100)),
                ('range_5_9', models.CharField(max_length=100)),
                ('range_10_14', models.CharField(max_length=100)),
                ('range_15_19', models.CharField(max_length=100)),
                ('range_20_24', models.CharField(max_length=100)),
                ('range_25_29', models.CharField(max_length=100)),
                ('range_30_34', models.CharField(max_length=100)),
                ('range_35_39', models.CharField(max_length=100)),
                ('range_40_44', models.CharField(max_length=100)),
                ('range_45_49', models.CharField(max_length=100)),
                ('range_50_54', models.CharField(max_length=100)),
                ('range_55_59', models.CharField(max_length=100)),
                ('range_60_64', models.CharField(max_length=100)),
                ('range_65_69', models.CharField(max_length=100)),
                ('range_70_74', models.CharField(max_length=100)),
                ('range_75_79', models.CharField(max_length=100)),
                ('range_80_plus', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationProjectionsBySpecialAgeGroups',
            fields=[
                ('selected_age_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('under_1', models.CharField(max_length=100)),
                ('range_1_2', models.CharField(max_length=100)),
                ('range_3_5', models.CharField(max_length=100)),
                ('range_6_13', models.CharField(max_length=100)),
                ('range_14_17', models.CharField(max_length=100)),
                ('range_18_24', models.CharField(max_length=100)),
                ('range_18_34', models.CharField(max_length=100)),
                ('range_less_18', models.CharField(max_length=100)),
                ('range_18_plus', models.CharField(max_length=100)),
                ('range_15_49', models.CharField(max_length=100)),
                ('range_15_64', models.CharField(max_length=100)),
                ('range_65_plus', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
