# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='By_Sex_And_Age_Groups',
        #     fields=[
        #         ('group_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('female', models.IntegerField()),
        #         ('male', models.IntegerField()),
        #         ('total_population', models.IntegerField()),
        #         ('age_group', models.CharField(max_length=100)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='By_Sex_And_School_Attendance',
        #     fields=[
        #         ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('education_level', models.CharField(max_length=100)),
        #         ('female', models.IntegerField()),
        #         ('male', models.IntegerField()),
        #         ('total_population', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='By_Type_of_Disability',
        #     fields=[
        #         ('disability_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('disability', models.IntegerField()),
        #         ('females', models.IntegerField()),
        #         ('males', models.IntegerField()),
        #         ('total_population', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Distribution_By_Sex_Number_Of_Households_Area_And_Density',
        #     fields=[
        #         ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('area_in_square_km', models.DecimalField(decimal_places=2, max_digits=30)),
        #         ('county', models.CharField(max_length=100)),
        #         ('density', models.DecimalField(decimal_places=7, max_digits=30)),
        #         ('female', models.IntegerField()),
        #         ('male', models.IntegerField()),
        #         ('no_of_houseHolds', models.IntegerField()),
        #         ('total_population', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Households_By_Main_Source_of_Water',
        #     fields=[
        #         ('source_of_water_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('source', models.CharField(max_length=100)),
        #         ('total', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Households_Main_Type_Floor_Material_Main_Dwelling_Unit',
        #     fields=[
        #         ('floor_material_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('material', models.CharField(max_length=100)),
        #         ('households', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Percentage_Of_Households_By_Ownership_Of_Household_Assets',
        #     fields=[
        #         ('ownership_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('asset', models.CharField(max_length=100)),
        #         ('percentage', models.DecimalField(decimal_places=5, max_digits=30)),
        #     ],
        # ),
    ]
