# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_months'),
        ('population', '0004_distribution_sex_number_households_area_density'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_Sex_Number_Households_Area_Density',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_in_square_km', models.DecimalField(decimal_places=2, max_digits=30)),
                ('county_name', models.CharField(max_length=100)),
                ('density', models.DecimalField(decimal_places=7, max_digits=30)),
                ('female', models.IntegerField()),
                ('male', models.IntegerField()),
                ('no_of_houseHolds', models.IntegerField()),
                ('total_population', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
