# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0004_hospitalbedsandcots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('climate_rainfall_id', models.AutoField(primary_key=True, serialize=False)),
                ('rainfall_in_mm', models.FloatField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Rainfall_Ids',
            fields=[
                ('rainfall_id', models.AutoField(primary_key=True, serialize=False)),
                ('rainFall', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surface_Area_By_Category',
            fields=[
                ('surface_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_sq_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Surface_Area_By_Category_Ids',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('categories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('climate_temperature_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_celsius_degrees', models.FloatField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature_Ids',
            fields=[
                ('temperature_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperatures', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topography_Altitude',
            fields=[
                ('altitude_topography_id', models.AutoField(primary_key=True, serialize=False)),
                ('geography_type', models.CharField(max_length=100)),
                ('altitude_in_metres', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_and_climate.Temperature_Ids'),
        ),
        migrations.AddField(
            model_name='surface_area_by_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_and_climate.Surface_Area_By_Category_Ids'),
        ),
        migrations.AddField(
            model_name='surface_area_by_category',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties'),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='rainfall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_and_climate.Rainfall_Ids'),
        ),
    ]
