# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_and_climate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment_Impact_Assessments_By_Sector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=100)),
                ('environmental_impact', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='TrendsInEnvironmentAndNaturalResourcesGrossValueAdded',
        #     fields=[
        #         ('industry_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('industry', models.CharField(max_length=100)),
        #         ('value_added', models.BigIntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Wildlife_Population_Estimates_In_The_Kenya_Rangelands',
        #     fields=[
        #         ('species_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('animal', models.CharField(max_length=100)),
        #         ('no_estimate', models.IntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
    ]
