# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment_and_natural_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average_Export_Prices_Ash',
            fields=[
                ('average_id', models.AutoField(primary_key=True, serialize=False)),
                ('soda_ash', models.DecimalField(decimal_places=2, max_digits=65)),
                ('fluorspar', models.DecimalField(decimal_places=2, max_digits=65)),
                ('year', models.DateField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Development_Expenditure_Water',
        #     fields=[
        #         ('development_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.DateField()),
        #         ('water_development', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('training_of_water_development_staff', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('rural_water_supplies', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('miscellaneous_and_special_water_programmes', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('national_water_conservation_and_pipeline_corporation', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('irrigation_development', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('national_irrigation_board', models.DecimalField(decimal_places=2, max_digits=65)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Expenditure_Cleaning_Refuse',
        #     fields=[
        #         ('development_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.DateField()),
        #         ('refuse_removal', models.DecimalField(decimal_places=2, max_digits=65)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Government_Forest',
            fields=[
                ('govt_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('previous_plantation_area', models.DecimalField(decimal_places=2, max_digits=65)),
                ('area_planted', models.DecimalField(decimal_places=2, max_digits=65)),
                ('area_clear_felled', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Num_High_Risk_Environ_Impact',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('transport_and_communication', models.DecimalField(decimal_places=2, max_digits=65)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=65)),
                ('tourism', models.DecimalField(decimal_places=2, max_digits=65)),
                ('mining_and_quarrying', models.DecimalField(decimal_places=2, max_digits=65)),
                ('human_settlements_and_Infrastructure', models.DecimalField(decimal_places=2, max_digits=65)),
                ('agriculture_and_forestry', models.DecimalField(decimal_places=2, max_digits=65)),
                ('commerce_and_industry', models.DecimalField(decimal_places=2, max_digits=65)),
                ('water_resources', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Population_Wildlife',
            fields=[
                ('population_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('buffalo', models.DecimalField(decimal_places=2, max_digits=65)),
                ('burchell_zebra', models.DecimalField(decimal_places=2, max_digits=65)),
                ('eland', models.DecimalField(decimal_places=2, max_digits=65)),
                ('elephant', models.DecimalField(decimal_places=2, max_digits=65)),
                ('gerenuk', models.DecimalField(decimal_places=2, max_digits=65)),
                ('giraffe', models.DecimalField(decimal_places=2, max_digits=65)),
                ('grant_gazelle', models.DecimalField(decimal_places=2, max_digits=65)),
                ('grevy_zebra', models.DecimalField(decimal_places=2, max_digits=65)),
                ('hunters_hartebeest', models.DecimalField(decimal_places=2, max_digits=65)),
                ('impala', models.DecimalField(decimal_places=2, max_digits=65)),
                ('kongoni', models.DecimalField(decimal_places=2, max_digits=65)),
                ('kudu', models.DecimalField(decimal_places=2, max_digits=65)),
                ('oryx', models.DecimalField(decimal_places=2, max_digits=65)),
                ('ostrich', models.DecimalField(decimal_places=2, max_digits=65)),
                ('thomson_gazelle', models.DecimalField(decimal_places=2, max_digits=65)),
                ('topi', models.DecimalField(decimal_places=2, max_digits=65)),
                ('warthog', models.DecimalField(decimal_places=2, max_digits=65)),
                ('waterbuck', models.DecimalField(decimal_places=2, max_digits=65)),
                ('wildebeest', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity_Of_Total_Mineral',
            fields=[
                ('quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity_Value_Fish_Landed',
            fields=[
                ('quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Record_Sale_Goverment_Products',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('soft_wood', models.DecimalField(decimal_places=2, max_digits=65)),
                ('fuelwood_charcoal', models.DecimalField(decimal_places=2, max_digits=65)),
                ('power_and_telegraph', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Trends_Envi_Natural_Resources',
            fields=[
                ('trend_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('forestry_and_logging', models.DecimalField(decimal_places=2, max_digits=65)),
                ('fishing_and_aquaculture', models.DecimalField(decimal_places=2, max_digits=65)),
                ('mining_and_quarrying', models.DecimalField(decimal_places=2, max_digits=65)),
                ('water_supply', models.DecimalField(decimal_places=2, max_digits=65)),
                ('GDP_at_current_prices', models.DecimalField(decimal_places=2, max_digits=65)),
                ('resource_as_percent_of_GDP', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Value_Of_Total_Mineral',
            fields=[
                ('value_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('year', models.DateField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Water_Purification_Points',
        #     fields=[
        #         ('water_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.DateField()),
        #         ('water_purification_points', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('boreholes_total', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('public', models.DecimalField(decimal_places=2, max_digits=65)),
        #     ],
        # ),
    ]
