# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_and_natural_resources', '0002_average_export_prices_ash_development_expenditure_water_expenditure_cleaning_refuse_government_fores'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Development_Expenditure_Water',
        #     fields=[
        #         ('development_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.CharField(max_length=100)),
        #         ('water_development', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('training_of_water_development_staff', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('rural_water_supplies', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('miscellaneous_and_special_water_programmes', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('national_water_conservation_and_pipeline_corporation', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('irrigation_development', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('national_irrigation_board', models.DecimalField(decimal_places=2, max_digits=65)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Expenditure_Cleaning_Refuse',
        #     fields=[
        #         ('development_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.CharField(max_length=100)),
        #         ('refuse_removal', models.DecimalField(decimal_places=2, max_digits=65)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Water_Purification_Points',
        #     fields=[
        #         ('water_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('year', models.CharField(max_length=100)),
        #         ('water_purification_points', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('boreholes_total', models.DecimalField(decimal_places=2, max_digits=65)),
        #         ('public', models.DecimalField(decimal_places=2, max_digits=65)),
        #     ],
        # ),
    ]
