# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='County_Outpatient_Morbidity_Below_Five',
            fields=[
                ('morbidity_above_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='CountyOutpatientMorbidityAboveFive',
            fields=[
                ('morbidity_above_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('death_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('anaemia', models.IntegerField()),
                ('cancer', models.IntegerField()),
                ('heart_disease', models.IntegerField()),
                ('hiv_aids', models.IntegerField()),
                ('malaria', models.IntegerField()),
                ('menengitis', models.IntegerField()),
                ('other_accidents', models.IntegerField()),
                ('other_causes', models.IntegerField()),
                ('pneumonia', models.IntegerField()),
                ('road_traffic', models.IntegerField()),
                ('tuberclosis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseList',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('accidents', models.IntegerField()),
                ('other_diseases', models.IntegerField()),
                ('diarrhoea', models.IntegerField()),
                ('respiratory', models.IntegerField()),
                ('skin', models.IntegerField()),
                ('eye_infection', models.IntegerField()),
                ('intestinal_worms', models.IntegerField()),
                ('malaria', models.IntegerField()),
                ('pneumonia', models.IntegerField()),
                ('joint_pains', models.IntegerField()),
                ('uti', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facilities', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization_Rate',
            fields=[
                ('immunization_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Personnel',
            fields=[
                ('medical_personnel_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('bsc_nursing', models.IntegerField()),
                ('clinical_officers', models.IntegerField()),
                ('dentists', models.IntegerField()),
                ('doctors', models.IntegerField()),
                ('enrolled_nurses', models.IntegerField()),
                ('pharmacists', models.IntegerField()),
                ('pharmtech', models.IntegerField()),
                ('health_officer', models.IntegerField()),
                ('health_tech', models.IntegerField()),
                ('registered_nurse', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nhif_Members',
            fields=[
                ('nhif_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('formal_sector', models.IntegerField()),
                ('informal_sector', models.IntegerField()),
                ('total', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nhif_Resources',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50)),
                ('benefits', models.BigIntegerField()),
                ('contributions_net_benefits', models.BigIntegerField()),
                ('receipts', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('count_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcounty_id', models.IntegerField()),
                ('subcounty_name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.AddField(
            model_name='countyoutpatientmorbidityabovefive',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.DiseaseList'),
        ),
        migrations.AddField(
            model_name='county_outpatient_morbidity_below_five',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.DiseaseList'),
        ),
    ]
