# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20170908_1457'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Sectors',
        #     fields=[
        #         ('sector_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('sector_name', models.CharField(max_length=100)),
        #         ('dataset_title', models.CharField(max_length=100)),
        #     ],
        # ),
    ]
