# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBedsAndCots',
            fields=[
                ('bed_cot_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_county_id', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('cots', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
