# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_hospitalbedsandcots'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Sectors',
        #     fields=[
        #         ('sector_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('sector_name', models.CharField(max_length=100)),
        #         ('report', models.CharField(max_length=100)),
        #         ('coverage', models.CharField(max_length=100)),
        #         ('source', models.CharField(max_length=100)),
        #         ('table_name', models.CharField(max_length=100)),
        #         ('api_url', models.CharField(max_length=100)),
        #     ],
        # ),
    ]
