# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Use_Of_Contraception_By_County',
            fields=[
                ('contraception_id', models.AutoField(primary_key=True, serialize=False)),
                ('any_modem_method', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        # migrations.CreateModel(
        #     name='DistributionOfOutpatientVisitsByTypeOfHealthcareProvider_2013',
        #     fields=[
        #         ('health_facility_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('public', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('private', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('faith_based', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('others', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Insurance_Coverage_By_Counties_And_Types_2013',
        #     fields=[
        #         ('insurance_coverage_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('insured', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('nhif', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('cbhi', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('private', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('others', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Maternal_Care',
            fields=[
                ('maternal_care_id', models.AutoField(primary_key=True, serialize=False)),
                ('percent_receiving_antenatal_care_from_a_skilled_provider', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_delivered_in_a_health_facility', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_delivered_by_a_skilled_provider', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Nutritional_Status_Of_Children',
            fields=[
                ('nutrition_child_id', models.AutoField(primary_key=True, serialize=False)),
                ('stunted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wasted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('under_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Nutritional_Status_Of_Women',
            fields=[
                ('nutrition_adult_id', models.AutoField(primary_key=True, serialize=False)),
                ('undernutrition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overweight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obese', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Registered_Medical_Laboratories_By_Counties_2016',
        #     fields=[
        #         ('reg_med_lab_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('class_a', models.IntegerField()),
        #         ('class_b', models.IntegerField()),
        #         ('class_c', models.IntegerField()),
        #         ('class_d', models.IntegerField()),
        #         ('class_e', models.IntegerField()),
        #         ('class_f', models.IntegerField()),
        #         ('unknown', models.IntegerField()),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Use_Of_Mosquito_Nets_By_Children',
        #     fields=[
        #         ('use_mosquito_net_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('children_under_five_years_who_slept_under_llin_last_night', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
        #     ],
        # ),
    ]
