# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_hiv_aids_awareness_and_testing_registered_active_nhif_members_by_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionOfOutpatientVisitsByTypeOfHealthcareProvider',
            fields=[
                ('health_facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('public', models.DecimalField(decimal_places=2, max_digits=10)),
                ('private', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faith_based', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Coverage_By_Counties_And_Types',
            fields=[
                ('insurance_coverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('insured', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nhif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cbhi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('private', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Medical_Laboratories_By_Counties',
            fields=[
                ('reg_med_lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_a', models.IntegerField()),
                ('class_b', models.IntegerField()),
                ('class_c', models.IntegerField()),
                ('class_d', models.IntegerField()),
                ('class_e', models.IntegerField()),
                ('class_f', models.IntegerField()),
                ('unknown', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Use_Of_Mosquito_Nets_By_Children',
            fields=[
                ('use_mosquito_net_id', models.AutoField(primary_key=True, serialize=False)),
                ('children_under_five_years_who_slept_under_nets_last_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
    ]
