# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_distributionofoutpatientvisitsbytypeofhealthcareprovider_insurance_coverage_by_counties_and_types_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Active_Nhif_Members_By_County',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('formal', models.IntegerField()),
                ('informal', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Active_Nhif_Members_Nationally',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('formal', models.IntegerField()),
                ('informal', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
