# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_fertility_by_education_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertility_Rate_By_Age_And_Residence',
            fields=[
                ('fertility_id', models.AutoField(primary_key=True, serialize=False)),
                ('fertility_rate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('age_group', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
