# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_percentage_adults_who_are_current_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage_Incidence_Of_Diseases_In_Kenya',
            fields=[
                ('incidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage_incidence', models.DecimalField(decimal_places=1, max_digits=10)),
                ('disease', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
