# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_percentage_incidence_of_diseases_in_kenya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage_Who_Drink_Alcohol_By_Age',
            fields=[
                ('percentage_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=10)),
                ('women', models.DecimalField(decimal_places=1, max_digits=10)),
                ('men', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
