# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_place_of_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevalence_Of_Overweight_And_Obesity',
            fields=[
                ('prevalence_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_group', models.CharField(max_length=10)),
                ('women', models.IntegerField()),
                ('men', models.IntegerField()),
                ('total', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
