# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Average_Retail_Prices_Of_Selected_Petroleum_Products',
            fields=[
                ('retail_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('petroleum_product', models.CharField(max_length=100)),
                ('retail_price_ksh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='Net_Domestic_Sale_Of_Petroleum_Fuels_By_Consumer_Category',
        #     fields=[
        #         ('net_sale_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('consumer', models.CharField(max_length=100)),
        #         ('net_sale', models.IntegerField()),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
    ]
