# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_average_retail_prices_of_selected_petroleum_products_net_domestic_sale_of_petroleum_fuels_by_consume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_Demand_And_Supply',
            fields=[
                ('electricity_id', models.AutoField(primary_key=True, serialize=False)),
                ('demand_supply', models.CharField(max_length=100)),
                ('capacity_megawatts', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generation_And_Imports_Of_Electricity',
            fields=[
                ('electricity_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('electricity_source', models.CharField(max_length=100)),
                ('capacity_megawatts', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Installed_And_Effective_Capacity_Of_Electricity',
            fields=[
                ('capacity_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('electricity_source', models.CharField(max_length=100)),
                ('capacity_megawatts', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Net_Domestic_Sale_Of_Petroleum_Fuels_By_Consumer_Category',
            fields=[
                ('domestic_sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('quantity_tonnes', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Petroleum_Supply_And_Demand',
            fields=[
                ('petroleum_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('petroleum_product', models.CharField(max_length=100)),
                ('quantity_tonnes', models.DecimalField(decimal_places=4, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Value_And_Quantity_Of_Imports_Exports',
            fields=[
                ('petroleum_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('petroleum_product', models.CharField(max_length=100)),
                ('quantity_tonnes', models.IntegerField()),
                ('value_millions', models.DecimalField(decimal_places=4, max_digits=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
