# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('buildingandconstruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Counties')),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Id',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_and_construction.Industry_Id'),
        ),
    ]
