# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_and_construction', '0002_quarterly_civil_engineering_cost_index_quarterly_non_residential_buid_cost_index_quarterly_overall_c'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Quarterly_Civil_Engineering_Cost_Index',
        #     fields=[
        #         ('cost_index_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('march', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('june', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('sept', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('december', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Quarterly_Non_Residential_Build_Cost',
        #     fields=[
        #         ('cost_index_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('march', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('june', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('sept', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('december', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Quarterly_Overal_Construction_Cost',
        #     fields=[
        #         ('category_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('march', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('june', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('sept', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('december', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Quarterly_Residential_Bulding_Cost',
        #     fields=[
        #         ('building_construction_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('category', models.CharField(max_length=100)),
        #         ('march', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('june', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('september', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('december', models.DecimalField(decimal_places=2, max_digits=2)),
        #         ('year', models.IntegerField()),
        #     ],
        # ),
    ]
